### ISSUE TITLE
How to disable logs?

### ISSUE THREAD

**Issue by yauheniprakapenka** [peiffer-innovations/template_expressions#81]
Hi there!

Thanks for your library. It will be great if it will be able to disable logging for template_expressions. I would like to focus on errors in the console, reducing the spam logs

![image](https://github.com/user-attachments/assets/d94d9168-c502-446c-85e8-b6243d3799c1)

**Comment by jpeiffer** [comment]
It uses the [logging](https://pub.dev/packages/logging) package.  So where you register your listener to the log stream you can ignore the logs from the loggers you don't care about.  Or, you can set the level to something more like INFO rather than ALL or FINEST.  Setting the logger level to one of those two is almost always noisy because it's meant to give as much information as possible to help diagnose any potential issues.
